// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Ce8R_W-PcDKzsJAEXYFFY-hrK296wkw',
    appId: '1:540322584393:web:4ba625c90dadffcd2d2c98',
    messagingSenderId: '540322584393',
    projectId: 'pi-sistema-de-ia',
    authDomain: 'pi-sistema-de-ia.firebaseapp.com',
    storageBucket: 'pi-sistema-de-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7MR35A7m0ZHrj3MCUzW0nESuEkzk9Bs',
    appId: '1:540322584393:android:de5ae7f3166e90082d2c98',
    messagingSenderId: '540322584393',
    projectId: 'pi-sistema-de-ia',
    storageBucket: 'pi-sistema-de-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ_Dd5oLg8aKgZZWwYVH78vfHl8cMbxvs',
    appId: '1:540322584393:ios:726ee1585c89a2bb2d2c98',
    messagingSenderId: '540322584393',
    projectId: 'pi-sistema-de-ia',
    storageBucket: 'pi-sistema-de-ia.firebasestorage.app',
    iosBundleId: 'com.uptap.facelock.pi2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ_Dd5oLg8aKgZZWwYVH78vfHl8cMbxvs',
    appId: '1:540322584393:ios:726ee1585c89a2bb2d2c98',
    messagingSenderId: '540322584393',
    projectId: 'pi-sistema-de-ia',
    storageBucket: 'pi-sistema-de-ia.firebasestorage.app',
    iosBundleId: 'com.uptap.facelock.pi2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Ce8R_W-PcDKzsJAEXYFFY-hrK296wkw',
    appId: '1:540322584393:web:b2e6aebfd01fe47c2d2c98',
    messagingSenderId: '540322584393',
    projectId: 'pi-sistema-de-ia',
    authDomain: 'pi-sistema-de-ia.firebaseapp.com',
    storageBucket: 'pi-sistema-de-ia.firebasestorage.app',
  );
}
